[project]
name = "rs-bidsify"
version = "0.1.0"
description = "'BIDS-ifys' raw resting-state EEG data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.10.1",
    "mne>=1.12.1",
    "mne-bids[full]>=0.18.0",
    "pandas[excel]>=3.0.2",
    "pydantic>=2.13.3",
    "pyyaml>=6.0.3",
    "typer>=0.25.1",
]

[dependency-groups]
dev = [
    {include-group = "lint"},
    {include-group = "test"},
    {include-group = "type_check"},
    {include-group = "nox"},
]
lint = [
    "ruff>=0.15.13",
]
nox = [
    "nox-uv>=0.8.0",
]
test = [
    "pyfakefs>=6.2.0",
    "pytest>=9.0.3",
    "pytest-mock>=3.15.1",
]
type_check = [
    "pyright>=1.1.409",
]

[project.scripts]
rs-bidsify = "rs_bidsify.main:app"

[project.optional-dependencies]
notebook = [
    "ipykernel>=7.2.0",
]

[build-system]
requires = ["uv_build>=0.11.8,<0.12"]
build-backend = "uv_build"

[tool.ruff]
extend-exclude = [
    "*.ipynb",
    "noxfile.py",
]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "A",
    "D",
    "E",
    "F",
    "I",
    "UP",
    "B",
    "SIM",
]

ignore = [
    "D100",
    "D104",
    "D105",
    "D107",

]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D"]
