name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-analysis:
    name: Check - ${{ matrix.options }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        options: [lint, type_check]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2
        
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Install nox
        run: uv tool install nox --with nox-uv

      - name: Run ${{ matrix.options }}
        run: nox -s ${{matrix.options}}

  test:
    name: Test (Python ${{ matrix.python-version }} - ${{ matrix.os }})
    needs: static-analysis
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13", "3.14"]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      
      - name: Install nox
        run: uv tool install nox --with nox-uv

      - name: Run Tests
        run: nox -s test --python ${{ matrix.python-version }}